[serviceweaver]
binary = "./weaver-app"

[single]
listeners.reverser = {address = "localhost:9000"}

[multi]
listeners.reverser = {address = "localhost:9000"}

[kube]
listeners.reverser = {public = true}
# To upload the image to another registry, check `weaver kube deploy -h`.
image = "docker.io/rgrandl27/weaver-app"
